# Generated by Django 4.2.10 on 2024-02-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=300)),
                ('char_id', models.IntegerField()),
                ('wallet', models.JSONField()),
                ('loyalty_points', models.JSONField()),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
                ('pull_data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=300)),
                ('corp_id', models.IntegerField()),
                ('offers', models.JSONField()),
            ],
        ),
    ]
