# Generated by Django 4.2.10 on 2024-02-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=300)),
                ('corp_id', models.IntegerField()),
                ('wallet_divisions', models.JSONField()),
                ('hangar_divisions', models.JSONField()),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
