# Generated by Django 4.2.10 on 2024-02-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp_trader', '0003_delete_corporationdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterWallet',
            new_name='CharacterData',
        ),
        migrations.RenameModel(
            old_name='LoyaltyStore',
            new_name='NPCCorpData',
        ),
    ]
