# Generated by Django 4.2.10 on 2024-03-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp_trader', '0004_rename_characterwallet_characterdata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterData',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='NPCCorpData',
            new_name='Corp',
        ),
    ]
