# Generated by Django 4.2.10 on 2024-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_trader', '0006_corp_is_npc_corp_alter_character_pull_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('item_id', models.IntegerField()),
                ('market_price', models.JSONField()),
                ('last_updated', models.DateTimeField(verbose_name='Last Updated')),
                ('pull_data', models.BooleanField(default=True)),
            ],
        ),
    ]
