# Generated by Django 4.2.10 on 2024-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp_trader', '0007_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='corp',
            name='lp_exchange_rate',
            field=models.FloatField(default=0.8),
        ),
    ]
